name: 'Feishu Notify Action'
description: 'Send message to Feishu bot via webhook'
branding:
  color: 'blue'
  icon: 'message-square'
author: 'xavier'
inputs:
  webhook:
    description: 'Feishu Webhook URL'
    required: true
  type:
    description: 'Message type'
    required: true
  message:
    description: 'Message to send'
    required: true
  secret:
    description: 'Feishu secret key (optional, for signature)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
